name: Build docker image

on:
  push:
    branches:
      - ${CI_REPO_DEFAULT_BRANCH}

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_DOCKER_USERNAME }}
          password: ${{ secrets.HUB_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.tags.outputs.tags }}
          push: true

      # - name: Read tags from file
      #   id: tags
      #   run: |
      #     TAGS=$(cat .tags)
      #     echo "::set-output name=tags::$TAGS"