name: Build docker image

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: docker-build
    container:
      image: catthehacker/ubuntu:act-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_DOCKER_USERNAME }}
          password: ${{ secrets.HUB_DOCKER_PASSWORD }}

      - name: Generate date-based tag
        id: new-tag
        run: |
          NEWTAG=$(env TZ=Europe/Moscow date +%y%m%d%H%M)
          echo "Generated tag: $NEWTAG"
          echo "::set-output name=tag::$NEWTAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            es1n/ghfollow:${{ steps.new-tag.outputs.tag }}
            es1n/ghfollow:latest
          push: true
